import Head from 'next/head';
import Link from 'next/link';

import products from '../products.json';
import { fromImageToUrl } from '../utils/urls';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Next.js with tailwindcss</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div className='grid grid-cols-4 gap-4'>
				{products?.data.map((product) => (
					<div key={product?.id}>
						<Link href={`/products/${product?.attributes?.slug}`}>
							<div className='cursor-pointer'>
								<img
									className='h-auto w-full object-cover'
									src={fromImageToUrl(
										product?.attributes?.image
									)}
									alt={product?.attributes?.alternativeText}
								/>
								<h3 className='text-3xl font-bold'>
									{product?.attributes?.name}
								</h3>
							</div>
						</Link>
					</div>
				))}
			</div>
		</div>
	);
}
