import Head from 'next/head';

import products from '../products.json';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			{products?.data.map((product) => (
				<div key={product.id}>{product?.attributes?.name}</div>
			))}
		</div>
	);
}
